### PR TITLE
Correction re founding members

### PR DESCRIPTION
**Pull request by SMuldowney**
Hi Mike, 

Sile Carroll here. We are doing some work on social media and this error was brought to my attention. I thought i would try and upskill during lockdown and try update it myself.

Thanks, 
Sile

### CODE REVIEW

**Comment by mgriffin** [comment]
Hey Sile!

The images just need to be moved into the `assets/images/` folder and then this is ✨ I can move them for you if you'd like, or if you want to take a stab at it, fire away.

**Comment by SMuldowney** [comment]
Hey Mike,

Thanks. I knew I had to fix that but I got tired of it the other night and
gave it up. Didn't realise you had seen this. It would be great if you
could do it for me and I'll have a stab at it next time.
Thanks a million!
Síle

**Comment by mgriffin** [comment]
No problem. I'll merge this and make the changes in another PR.

I've also invited you to let you make PRs directly in this repository if you need to make any other changes.

**Comment by SMuldowney** [comment]
Hi,

That's great. Thanks a million Mike!

Síle

**Pull request merged**
