### PR TITLE
Adding club xc 2017 results

### PR DESCRIPTION
**Pull request by hootsmin**

### CODE REVIEW

**Comment by mgriffin** [comment]
Looks pretty good 👍 

Can you change the times to include `m` and `s`, so make it `25m 33s` instead of `25.33`. Otherwise any trailing zeroes get dropped from the output.

**Comment by hootsmin** [comment]
Hey Mike, can you grant me the necessary permissions to merge pull requests? I promise I won't break things :)

**Comment by mgriffin** [comment]
@hootsmin Done, you should be able to merge pull requests now.

**Comment by Stevecoughlan123** [comment]
Matt and Mike

Thanks for this, I really appreciate it. I'm not sure why, but as yet I'm not seeing on the club website the commits from Matt on the club xc and winter league ? 

Most recent item I see is Damien's 4th place in national intermediate.

It may well be me , in which case sorry 

Steve

**Comment by mgriffin** [comment]
@Stevecoughlan123 It's because the pull request hasn't been merged yet. There's some work that needs to be done with it first, which I'll try and do this evening.

**Comment by Stevecoughlan123** [comment]
Sound as a pound Mike. If it helps any, I can forward you the WL in excel ? 

Steve

**Pull request merged**
