### PR TITLE
Create 2015-10-20-new-news-post.md

### PR DESCRIPTION
**Pull request by Stevecoughlan123**
Mike can u let me know by email if this test is successful please Steve

### CODE REVIEW

**Comment by mgriffin** [comment]
@Stevecoughlan123 Looks good, Steve.

**Comment by mgriffin** [comment]
You can see it in all its glory at http://liffeyvalleyac.com/news/2015/10/20/new-news-post/

**Comment by Stevecoughlan123** [comment]
Result !!! Cheers and thanks Mike 😉

**Comment by paulbalfe** [comment]
Hi Mike, I've also added a new post containing the Timetable for tomorrow's
races..if you can review & publish - thanks.

Paul

On Wed, Jun 29, 2016 at 10:12 PM, Stevecoughlan123 <notifications@github.com
> wrote:

> Result !!! Cheers and thanks Mike 😉
>
> Sent from my iPad
>

**Comment by Stevecoughlan123** [comment]
Hi mike

I created a new file there in the Liffey valley repository, but I tried to commit it direct to the master in stead of creating a pull request. Can you take a look at it and straighten it out if you can ? 

Cheers


Steve

**Comment by Stevecoughlan123** [comment]
Pull request created afterwards. Hope it's ok now. Let me know cheers

**Pull request merged**
