### PR TITLE
Update 2021-07-26-club-3k-results.md

### PR DESCRIPTION
**Pull request by galexandre**
Update of the times for the men 3000m.

### CODE REVIEW

**Comment by galexandre** [comment]
I am missing the times for the women 1500m. Does anyone know who has them?

**Comment by galexandre** [comment]
Time for the women pushed. I am not fully sure for the spelling of the different persons. Also, there is a time for a man missing I think (Cormac L.)

**Review by mgriffin — APPROVED** [review]

**Comment by galexandre** [comment]
All the missing men times has been pushed

**Comment by galexandre** [comment]
I don't have the rights to merge the MR. Can anyone merge it please?

**Comment by Stevecoughlan123** [comment]
Hi Geoffrey, it’s Steve here. Brigid Long, and Aisling McAleer are the two spellings I spotted.

Cheers.

**Comment by galexandre** [comment]
Hi @Stevecoughlan123 ,
Thank you for the review, I fixed the spellings mistake!

**Pull request merged**
