### PR TITLE
Adding post with link to Avondale Cup video.

### PR DESCRIPTION
**Pull request by hootsmin**

### CODE REVIEW

**Comment by hootsmin** [comment]
Hi @mgriffin, just wondering what your thoughts are on including links to videos on the site? Attempting to embed video in post from Vimeo with this PR.

**Comment by mgriffin** [comment]
Looks good 👍

**Comment by hootsmin** [comment]
Cheers @mgriffin. Assuming it's better to host this on something like Vimeo rather than in the repo in GitHub.

**Comment by mgriffin** [comment]
Yeah, I think it's better to host it on Vimeo. They have better controls for playback too, which make life easier for everyone.

**Pull request merged**
